export const routes = {
  setup: [
    { name: 'Getting Started', path: '/setup/getting-started' },
    { name: 'Theme Customization', path: '/setup/theme-customization' },
  ],
  design: [
    { name: 'Colors', path: '/design-system/colors' },
    { name: 'Typography', path: '/design-system/typography' },
    { name: 'Spacing', path: '/design-system/spacing' },
  ],
  components: [
    // { name: 'Active', path: '/components/active' },
    // { name: 'Alert', path: '/components/alert' },
    // { name: 'Anchor', path: '/components/anchor' },
    // { name: 'Badge', path: '/components/badge' },
    { name: 'Block', path: '/components/block' },
    // { name: 'Button', path: '/components/button' },
    // { name: 'Card', path: '/components/card' },
    // { name: 'Close', path: '/components/close' },
    // { name: 'Drawer', path: '/components/drawer' },
    // { name: 'Dropdown', path: '/components/dropdown' },
    { name: 'Flex', path: '/components/flex' },
    // { name: 'FormGroup', path: '/components/form-group' },
    { name: 'Icon', path: '/components/icon' },
    // { name: 'Input', path: '/components/input' },
    // { name: 'List', path: '/components/list' },
    // { name: 'Media', path: '/components/media' },
    // { name: 'Modal', path: '/components/modal' },
    // { name: 'Nav', path: '/components/nav' },
    // { name: 'Popover', path: '/components/popover' },
    // { name: 'Tabs', path: '/components/tabs' },
    { name: 'Text', path: '/components/text' },
    { name: 'Theme', path: '/components/theme' },
    // { name: 'Tooltip', path: '/components/tooltip' },
  ],
  principles: [
    { name: 'Library Principles', path: '/principles/library-principles' },
    { name: 'Component API Design', path: '/principles/api-design' },
    { name: 'Accessibility', path: '/principles/accessibility' },
  ],
}
